name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true

      - name: Set up store cache
        uses: actions/cache@v2
        with:
          path: store-cache
          key: nix-store

      - name: Build
        run: nix build -L

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: result/dist

      - name: Update store cache
        run: |
          sudo $(command -v nix) copy --to file://${PWD}/store-cache\?compression=none .#hakyll-site.env
          sudo $(command -v nix) copy --to file://${PWD}/store-cache\?compression=none .#hakyll-site

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: pages
          path: result

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: result
          target_branch: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true

      - name: Set up store cache
        uses: actions/cache@v2
        with:
          path: store-cache
          key: nix-store-posts

      - name: Build
        run: nix build .#posts -L

      - name: Update store cache
        run: |
          sudo $(command -v nix) copy --to file://${PWD}/store-cache\?compression=none .#posts.env
